### ISSUE TITLE
Cannot get m2k to run as User Job from MythTV

### ISSUE THREAD

**Issue by gnickoloff** [stuart-knock/myth2kodi#1]
Runs fine from command line, fails from User Job.

Checked that myth is set to run as mythtv user, changed permissions on myth2kodi and storage locations to eliminate that problem.

Checking the log files for myth and myth2kodi shows nothing helpful.

Any ideas that might help?

**Comment by stuart-knock** [comment]
I've never had an issue with it running as a MythTV User Job when it is working from the command line, so, I'm going to need some more information to be able to help you:
 
  + What exact command do you have as the MythTV user job.
  + By "fails from User Job", do you mean as a job run automatically after a recording finishes or clicking on the link on the page for the recording in MythWeb?
  + A diagnostics log might be useful too, that is, run ``myth2kodi --diagnostics`` and post the log.
  + Some general basic info will probably be useful too: OS; myth2kodi version; MythTV version...

**Comment by gnickoloff** [comment]
- Command: (Job #1 from MythTV) as   /usr/local/bin/myth2kodi "%DIR%/%FILE%" 
- Job #1 is set to run on recording profiles. It fails when it is supposed to run after recording and also when re-queued and from MythWeb. Both show "User Job returned non-zero, check logs" and the symlinks, file move, etc. do not occur
- Last diagnostic log attached.
- Running on Debian 8, 
Downloaded myth2kodi 2-3 days ago, to replace working mythicalLibrarian
MythTV is fixes/27 (I believe) from Debian Multimedia Repo.

I believe the script is being called (I put a line in that says: `echo "Made It!" >> /tmp/confirmation` near the top of the file and I am seeing "Made It!" in the file "/tmp/confirmation".but the script appears to not function. No log file information is generated.

I've checked all the storage directory permissions and the user 'mythtv' is owner/group. The myth2kodi script, mythTV backend are running under 'mythtv" user as well. I even assigned the bin/ files to 'mythtv' to see if that would help...but it did not.

If I run the myth2kodi script from a command line, all works as expected and the log file shows nothing unusual.

[diagnostics_2017-02-22T215649.log.txt](https://github.com/stuart-knock/myth2kodi/files/800245/diagnostics_2017-02-22T215649.log.txt)

**Comment by gnickoloff** [comment]
I don't think MythTV is passing %DIR%/%FILE% for some reason. I tried to echo $m2karg1 to a file at the beginning of the script, but got no output. Either I'm not doing it right, or the arguments are not coming over with the job command..... any ideas about that?

I don't know any way to turn that off or how it would not be working....

**Comment by stuart-knock** [comment]
I still do not have any good idea as to what might be going wrong here... I do have more questions.

Did you test with the ``echo "Made It!" >> /tmp/confirmation`` in the same location in the script as the ``echo $m2karg1``?
Because if ``$m2karg1`` is empty then that should still print a blank line in the file, or more specifically the ``\n`` character.

Do you get any log output at all for myth2kodi run, for example, from mythweb?
Because if it is just that ``$m2karg1`` is empty, then, myth2kodi will produce an error message in its log.

Did you grab a release or just clone the repo?

Could you enable debug level logging, set ``LOGLEVEL=3`` in your *myth2kodi.conf*, and process a recording at the command line and then a similar one through mythweb and post the complete log output for both?

**Comment by gnickoloff** [comment]
Yes. I just added $m2karg1 to the "Made it!" phrase. Made it gets echoed to the file... doesn't look like $m2karg1 does tho. I have a few more recordings to play with. I'll see what kind of output comes thru. when running the script manually.

I'm not seeing any log file output at all...unless I run the script manually. Then all the logged output is pretty much as expected. No indication of any problems/issues. Everything works as expected.

I don't recall. I'm pretty sure I installed an official release. Just to make sure, I'll reinstall, etc.

Debug level has been set to "3" for a couple of days now. I'll post the log file(s).

**Comment by gnickoloff** [comment]
Rearranged the "echo" statements in the script. Now has echo "Made it!" and then echo $m2karg1 as different statements: I'm seeing "Made it!" on one line, then a blank line for $m2karg1 each time the script runs. It seems to also show a blank line even when I run the script from a command line, so either I'm not echoing the variable correctly (e.g.` echo "$m2karg1" >> /tmp/confirmation `) or I am and the argument isn't passing....

Still seeing no log file at all for any after-record jobs or mythweb initiated jobs. No log file at all.
I have attached a log file from a command-line run of the script.

I reinstalled the official release of 1.2.2 before this last batch of attempts/tests. I may have installed a copy of the repository.

On a lark, I changed the shebang on the script to "#!/bin/bash" just to see if "env" was doing something funky.... no change.

[myth2kodi.log.txt](https://github.com/stuart-knock/myth2kodi/files/800846/myth2kodi.log.txt)
[confirmation.txt](https://github.com/stuart-knock/myth2kodi/files/800847/confirmation.txt)

**Comment by stuart-knock** [comment]
Yeah, weird... On the plus side, when it is running it seems to be working well.

Your echo for `$m2karg1` looks correct...
On what line number did you put the echo statements to confirmation.txt?
Line 5195 would be a good place in v1.2.2, after the declare but before the
call to m2k_init().

Could you try processing a recording by providing full path rather
than just the file name, in case the issue is somehow to do with that.
That is, run something like:
`
myth2kodi '/full/path/to/1484_20170225000000.mpg'
`
and post the log. 

And finally, while I know I just pushed you back onto the release,
could you grab the latest from the repo and try that and post the log?
I've been fixing some bugs for other users and, while I don't think
any of those issues are related to your issue, there are now more
logging statements as a result. I've also expanded on the diagnostics
checks a little, so it is probably worth running
`
myth2kodi --diagnostics
`
as a first step and checking that nothing new is picked-up.

**Comment by stuart-knock** [comment]
Inspired by your *echo* statements, I've just added a "we were called"
kind of message that will be written to a temporary file called:  
  `/tmp/m2k_init_pre_logging_debug.txt`
every time *myth2kodi* is run, as well as some extra info when debug
level logging is enabled. This covers the gap that was in the logs prior
to the logging system's initialisation.

The more I've thought about this the less I think it is possible for the
problem you are having to be in the *myth2kodi* script. It must be in
the way it is called from MythTV. This new temporary file output should
get at the missing information about what is going wrong. But as far as
I can tell, the only possible point of failure is that *myth2kodi* is called
by the "wrong" user. Is there any chance that your mythbackend is
running as a user other than `mythtv`? I have seen systems that by
default run the MythTV frontend as `mythtv` user but run the backend as
a different user called something like `mythbackend`. It is the user running
*mythbackend* that calls *myth2kodi*.

**Comment by gnickoloff** [comment]
Running with full path seems to behave indentically:

Log file and "confirm" file attached.

[myth2kodi_full-path.log.txt](https://github.com/stuart-knock/myth2kodi/files/803939/myth2kodi_full-path.log.txt)
[confirmation.txt](https://github.com/stuart-knock/myth2kodi/files/803940/confirmation.txt)

**Comment by gnickoloff** [comment]
I downloaded the new release (1.3.1) and tried again.

Calling from MythTV/mythweb still does essentially nothing. It starts the job, supposedly runs for a minute or two, then reports an unspecified error. it starts the job, but never does anything with a log file.

Running from the command line seems to work flawlessly.

Attached diagnostics log and debug log from command line run and the "echo confirmations file
[confirmation.diags & cmdln.txt](https://github.com/stuart-knock/myth2kodi/files/804121/confirmation.diags.cmdln.txt)

[m2k_init_pre_logging_debug.txt](https://github.com/stuart-knock/myth2kodi/files/804182/m2k_init_pre_logging_debug.txt)
[diagnostics.log.txt](https://github.com/stuart-knock/myth2kodi/files/804129/diagnostics.log.txt)
[diagnostics_2017-02-27T102117.log.txt](https://github.com/stuart-knock/myth2kodi/files/804131/diagnostics_2017-02-27T102117.log.txt)
[myth2kodi.log.txt](https://github.com/stuart-knock/myth2kodi/files/804136/myth2kodi.log.txt)

As far as I can tell, the MythBackend is running as 'mythtv". It is specified as such in the systemd script and seems to be when I inquire about running processes:

```
mythtv@bugs:/livetv $ ps -U mythtv
  PID TTY          TIME CMD
  451 ?        00:00:03 chrome
 1558 ?        00:00:00 systemd
 1559 ?        00:00:00 (sd-pam)
 1697 ?        00:00:01 gpg-agent
...
26710 ?        00:14:28 mythbackend
26738 ?        00:09:13 mythlogserver
....
```

I do notice that the argument ($m2karg1) never seem to make it to the "confirmation" log file.... not sure why that's happening. (or not happening)

**Comment by gnickoloff** [comment]
Maybe getting somewhere:

Changed the shebang on the latest release to #!/bin/sh and got some output in log files.... which is pretty strange to me.

```
[2017-02-27T14:47:54] DEBUG: ENTERING: log_rotation() ; CALLED FROM: m2k_init()
[2017-02-27T14:47:54] DEBUG: LOGFILE=/home/mythtv/.myth2kodi/myth2kodi.log-
[2017-02-27T14:47:54] DEBUG: LOGLEVEL=3-
[2017-02-27T14:47:54] DEBUG: LOGTYPE=filestderr-
[2017-02-27T14:47:54] DEBUG: ENTERING: validate_settings() ; CALLED FROM: m2k_init()
[2017-02-27T14:47:54] ERROR: 'FailSafeDir' is not a directory: /home/mythtv/FailSafe
[2017-02-27T14:47:54] DEBUG: myth2kodi script initialisation complete.
[2017-02-27T14:47:54] DEBUG: Running myth2kodi as mythtv
[2017-02-27T14:47:55] DEBUG: ENTERING: validate_args() ; CALLED FROM: main()
[2017-02-27T14:47:55] DEBUG: Called with 0 arguments. Called as:
       myth2kodi '' "" "" "" '' ''
[2017-02-27T14:47:55] ERROR: validate_args(): myth2kodi must be called with at least one argument.
[2017-02-27T14:47:55] DEBUG: ENTERING: msg_usage() ; CALLED FROM: validate_args()
[2017-02-27T14:47:55] DEBUG: ENTERING: exit_job() ; CALLED FROM: main()
       Called with 1 arguments
       arg 1 = InvalidCall
[2017-02-27T14:47:55] ERROR: exit_job() CALLED FROM: main(). myth2kodi called incorrectly: InvalidCall
[2017-02-27T14:47:55] DEBUG: Either: Notify=Disabled; scan mode; recording is in an ignore list; or NOTIFY_MSG was not set.
```

And, here is the "pre_logging" text log:

[m2k_init_pre_logging_debug.txt](https://github.com/stuart-knock/myth2kodi/files/804866/m2k_init_pre_logging_debug.txt)

Also:

I tried to re-queue myth2kodi on a recording that previously failed and got no logging activity from myth2kodi (e.g. no log file entry and no "pre-logging file") but I did see the following in the MythTV logfile:

```
2017-02-27 15:07:58.712570 I [26710/14624] UserJob_480 jobqueue.cpp:2409 (DoUserJobThread) - JobQueue: Started Myth2Kodi for "Face the Nation" recorded from channel 1111 at 2017-02-26T15:30:00Z
2017-02-27 15:07:58.712657 D [26710/14624] UserJob_480 mythsystemunix.cpp:790 (Fork) - Launching: /usr/local/bin/myth2kodi "/livetv/1111_20170226153000.mpg"
2017-02-27 15:07:58.719185 I [26710/14624] UserJob_480 mythsystemunix.cpp:886 (Fork) - Managed child (PID: 14625) has started! * command=/usr/local/bin/myth2kodi "/livetv/1111_20170226153000.mpg", timeout=0
2017-02-27 15:07:58.765360 I [26710/26732] SystemManager mythsystemunix.cpp:356 (run) - Managed child (PID: 14625) has exited! command=/usr/local/bin/myth2kodi "/livetv/1111_20170226153000.mpg", status=512, result=2
2017-02-27 15:07:58.808048 E [26710/14624] UserJob_480 jobqueue.cpp:2444 (DoUserJobThread) - JobQueue: User Job '/usr/local/bin/myth2kodi "/livetv/1111_20170226153000.mpg"' failed.

```

....so it seems that, at least in this case, the proper arguements were, indeed, passed to the m2k script.

Here is a similar entry (again, with no logging activity from m2k) for a job that was queued by the myth recording completing:

```
2017-02-27 15:30:16.666513 I [26710/19545] UserJob_483 jobqueue.cpp:2409 (DoUserJobThread) - JobQueue: Started Myth2Kodi for "The Rifleman":"The Coward" recorded from channel 1112 at 2017-02-27T20:17:00Z
2017-02-27 15:30:16.666598 D [26710/19545] UserJob_483 mythsystemunix.cpp:790 (Fork) - Launching: /usr/local/bin/myth2kodi "/livetv/1112_20170227201700.mpg"
2017-02-27 15:30:16.672358 I [26710/19545] UserJob_483 mythsystemunix.cpp:886 (Fork) - Managed child (PID: 25112) has started! * command=/usr/local/bin/myth2kodi "/livetv/1112_20170227201700.mpg", timeout=0
2017-02-27 15:30:16.717112 I [26710/26732] SystemManager mythsystemunix.cpp:356 (run) - Managed child (PID: 25112) has exited! command=/usr/local/bin/myth2kodi "/livetv/1112_20170227201700.mpg", status=512, result=2
2017-02-27 15:30:16.751588 E [26710/25111] UserJob_483 jobqueue.cpp:2444 (DoUserJobThread) - JobQueue: User Job '/usr/local/bin/myth2kodi "/livetv/1112_20170227201700.mpg"' failed.
```

**Comment by stuart-knock** [comment]
This gets us closer to an answer.

Firstly, the reason your confirmation echo shows nothing for m2karg1 is just that it is placed in the script before that variable is set. The `m2k_init_pre_logging_debug.txt` file you attached for the first run with v1.3.1 shows that the first argument is making it into the script.

Secondly, the `sh` check was interesting, on my system that would have had no effect because `sh` just redirects to `bash`. However, as the script uses bash specific constructs, a failure using a different shell is to be expected.

Now, as you can see from the `m2k_init_pre_logging_debug.txt` you posted running with `sh`, the next line in that file should be `Config complete.`
There are 3 things between the last message you get and the next one which you do not. That is: `m2kdir`; `myth2kodi.conf`; and `source`. I've just pushed a commit to the repo that added
an extra line to `m2k_init_pre_logging_debug.txt` containing the value for the working directory `m2kdir`. So if you grab the latest `myth2kodi` from the repo and queue processing on a recording, and post the resulting `m2k_init_pre_logging_debug.txt`, then we can see how that is set.

Could you also post your `myth2kodi.conf`, and tell me the full path to the file you are posting?

Hopefully we can identify the problem with that, because if `source` is not working properly, and not working only when called via MythTV, then I have no idea how to proceed...

**Comment by stuart-knock** [comment]
Now I'm not certain that the "only sets the `HOME` variable for login shells" is true. So, let's just start with the info I requested in my previous post and go from there...

~~Ok, I think I have it, debian only sets the `HOME` variable for login shells, so it is set from the command line but not for a job called from MythTV. So your output for the new entry in pre-logging will be: `'/.myth2kodi'`  or  `/root/.myth2kodi` rather than `/home/mythtv/.myth2kodi`.~~

~~If this is the case, then a quick fix would be to set `m2kdir="/home/mythtv/.myth2kodi"` on line 292 of `myth2kodi`. NOTE: this prevents anyone else, other than the `mythtv` user,  from calling `myth2kodi`~~

**Comment by gnickoloff** [comment]
I have downloaded the new revision and will proceed shortly.

Here are the script and config. files:

[myth2kodi_(script).txt](https://github.com/stuart-knock/myth2kodi/files/805534/myth2kodi_.script.txt)
Path for the script on my system is "/usr/local/bin"

[myth2kodi.conf.txt](https://github.com/stuart-knock/myth2kodi/files/805533/myth2kodi.conf.txt)
Path for config. file on my system is "/home/mythtv/.myth2kodi/"

A couple of notes, etc:

- I think the instance where the argument was passed into the "pre-log" text file was a "left-over" from a command line run. I've noticed that when called from mythtv, the "pre-logging" file is not created, neither is the log.
- I just tried moving the echo statements to just after where the variables are assigned from the arguments (#5467?)...still nothing is echoed. I also added a line immediately before telling me which line number is being echoed..this also fails to be seen in the output file, so I think there is some kind of failure that comes before which prevents the echo (and the rest of the script) from working.
- As far as bash vs. sh, etc... The default shell is bash for this user I believe, so I'd expect a job called from MythTV would be using bash as well. I'm not sure tho.
- I believe that I replaced $HOME and "~" with "/home/mythtv/" early on in trying to get this working. I may have missed an instance or something.

**Comment by gnickoloff** [comment]
Looking at the copy of the M2K script I sent over, I noticed that I put the second set of echos in a "TODO" version of the main code. I moved it a few lines later in the newest version of the script and ran the script from the Myth job queue.
The file name argument was successfully passed to the script and was echoed in the "confirmation" file.
```
Ln. 2 'Here we go!' 
Ln. 5467 'Bef. Main' 
ARG1[ /livetv/1361_20170227220000.mpg ]
```
It appears that there was no myth2kodi.log file created for this run.

Here is the contents of the "pre-log" file:
```
Entered m2k_init() -- Mon Feb 27 21:06:05 EST 2017
Called with 1 arguments. Called as:
  myth2kodi '/livetv/1361_20170227220000.mpg' "" "" "" '' ''
Working directory: '/home/mythtv/.mythtv/.myth2kodi'
```

Here is the relevant portion of the mythtv log file:
```
2017-02-27 21:06:04.990767 I [26710/20387] UserJob_534 mythsystemunix.cpp:886 (Fork) - Managed child (PID: 20388) has started! * command=/usr/local/bin/myth2kodi "/livetv/1361_20170227220000.mpg", timeout=0
....
2017-02-27 21:08:13.666683 I [26710/26732] SystemManager mythsystemunix.cpp:356 (run) - Managed child (PID: 20388) has exited! command=/usr/local/bin/myth2kodi "/livetv/1361_20170227220000.mpg", status=256, result=1
2017-02-27 21:08:13.670183 E [26710/20387] UserJob_534 jobqueue.cpp:2444 (DoUserJobThread) - JobQueue: User Job '/usr/local/bin/myth2kodi "/livetv/1361_20170227220000.mpg"' failed.
```
Still returning "status=256, result=1"...with a whole bunch of TVDB requests and the Myth housekeeping routine in between the above statements.

So it appears that the argument(s) is/are being passed to the script and the script is starting and running at least up to the point where the arguments are assigned to appropriate variables, but before writing the log file.

**Comment by gnickoloff** [comment]
I ran the same recording from the command line. Here are the output files:

confirmation
```
Ln. 2 'Here we go!' 
Ln. 5467 'Bef. Main' 
ARG1[ /livetv/1361_20170227220000.mpg ]
```
myth2kodi.log:
[myth2kodi.log.txt](https://github.com/stuart-knock/myth2kodi/files/805619/myth2kodi.log.txt)

**Comment by stuart-knock** [comment]
There is the problem. 
You said your config script is in `/home/mythtv/.myth2kodi/`, but the myth2kodi working directory when called from MythTV is `/home/mythtv/.mythtv/.myth2kodi`. And that is where `myth2kodi` looks for its .conf file.

For this to happen it must mean that `$HOME` when called via MythTV is set to `/home/mythtv/.mythtv` for some reason...

Also, up until now, any calls of `myth2kodi` from MythTV will have written any logs to
 `/home/mythtv/.mythtv/.myth2kodi/myth2kodi.log`, though I suspect there is something odd in
 `/home/mythtv/.mythtv/.myth2kodi/myth2kodi.conf` which is causing the failure before `myth2kodi`'s logging system gets started.

I'm not sure there is a good way, or that it is a good idea, to override `HOME` in the myth2kodi script.
So, there are two possible work-arounds I can think of for you, either:
  1. On `line 292` of the `myth2kodi` script, set `m2kdir="/home/mythtv/.myth2kodi"` ; **or**
  2. Make a symbolic link to `/home/mythtv/.myth2kodi` from `/home/mythtv/.mythtv/.myth2kodi`, that is run, `ln -s /home/mythtv/.myth2kodi /home/mythtv/.mythtv/.myth2kodi`. You should check and move or delete the existing `/home/mythtv/.mythtv/.myth2kodi` directory first. 

Option **1** restricts the `myth2kodi` script to only being called by the user `mythtv` and you will have to remember to make the change in any future version of `myth2kodi` that you download. But it is simple, and tested.
Option **2** should mean that, run at command line or by MythTV, `myth2kodi` will always see the same working directory when called by the `mythtv` user. This does not have the restriction that the only user able to call `myth2kodi` is `mythtv`. It also has the advantage that you will not have to modify any future versions of `myth2kodi` you download, as you would with option **1**. As far as I know, there is nothing in the `myth2kodi` script that should have a problem with the working directory being a link to the directory rather than the directory itself, though this is not tested. Apart from the fact I have not tried this, I think it is the better option if it works.

I guess you could also look into how and why `HOME` is being set the way it is by MythTV, though for that I can't be of much help.

Either way, you should also not use `$HOME` for setting any of your paths. At the moment the only other correction I think you will need seems to be `FailSafeDir` in your .conf file.

**Comment by gnickoloff** [comment]
I created a symlink from /.mythtv/.myth2kodi -> /.myth2kodi.  It looks promising. I was able to queue up a job from MythWeb and it ran successfully.
I'm going to dig deeper into it and confirm, etc. a little bit later.

**Comment by gnickoloff** [comment]
I found the source of the $HOME directory error and fixed that. 
Myth2Kodi seems to be working well now in all contexts.

Thank you for your help with this. It was giving me fits.
